### ISSUE TITLE
Placeholder resolver casts everything into strings

### ISSUE THREAD

**Issue by aurmil** [dflydev/dflydev-dot-access-configuration#5]
hello

I think the title is self-explanatory

YAML

``` yaml
test : true
test2 : 2015
```

exportRaw()

> 'test' => boolean true
> 'test2' => int 2015

export()

> 'test' => string '1' (length=1)
> 'test2' => string '2015' (length=4)

should not https://github.com/dflydev/dflydev-dot-access-configuration/blob/master/src/Dflydev/DotAccessConfiguration/AbstractConfiguration.php#L155 be 

``` php
if (is_string($input)) {
```

?

cause troubles with value+type comparison

regards

**Comment by simensen** [comment]
@aurmil Would you be interested in submitting a PR to address this? I think that `is_string($input)` should work. If you could add some test cases that address this it would make me feel better knowing that it will continue to work as advertised.

Thanks!
